apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "demo-helm.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "demo-helm.fullname" . }}
              servicePort: http
